"""Migration of my database

Revision ID: 1974d8c808cd
Revises: 
Create Date: 2024-09-21 21:41:29.157171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1974d8c808cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.drop_column('color_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_id', mysql.VARCHAR(length=2), nullable=True))

    # ### end Alembic commands ###
